[workspace]
resolver = "2"
members = ["crates/core", "crates/host"]
default-members = ["crates/host"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "Apache-2.0"
publish = false

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"

[workspace.dependencies]
shinbo-core = { path = "crates/core" }
