import assert from "node:assert/strict";
import fs from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { listNotes } from "../main/vault";
import { type VaultChoice } from "../shared/vault";

test("listing notes yields while reading bodies and preserves complete metadata and fresh changes", async (t) => {
  const root = fs.mkdtempSync(path.join(tmpdir(), "shinbo-note-list-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const folder = path.join(root, "notes");
  fs.mkdirSync(folder);
  fs.mkdirSync(path.join(folder, "Research"));
  fs.mkdirSync(path.join(folder, "attachments"));
  fs.writeFileSync(path.join(folder, "attachments", "shot.png"), "fixture");
  const text = (index: number) => `---\ntitle: "Note ${index} 日本語"\nkind: "note"\nsaved: "2026-09-12T00:00:${String(index).padStart(2, "0")}.000Z"\ntags: ["research"]\nsource: "https://example.com"\napplication: "Fixture"\n---\n${"Body text. ".repeat(3000)}\n![[attachments/shot.png]]\n`;
  for (let index = 0; index < 40; index++) fs.writeFileSync(path.join(folder, "Research", `note-${index}.md`), text(index));
  fs.writeFileSync(path.join(folder, "incomplete.md"), "---\nkind: note\n");
  const vault: VaultChoice = { root, folder: "notes", name: "Fixture", kind: "folder" };
  const syncReads = t.mock.method(fs, "readFileSync");
  let yielded = false;
  setImmediate(() => { yielded = true; });
  const notes = await listNotes(vault);
  assert.equal(yielded, true);
  assert.equal(syncReads.mock.callCount(), 0);
  assert.equal(notes.length, 40);
  assert.deepEqual(notes.map((note) => note.title), Array.from({ length: 40 }, (_, index) => `Note ${39 - index} 日本語`));
  assert.equal(notes[0].relative, "Research/note-39.md");
  assert.equal(notes[0].folder, "Research");
  assert.deepEqual(notes[0].tags, ["research"]);
  assert.equal(notes[0].sourceUrl, "https://example.com");
  assert.equal(notes[0].sourceApplication, "Fixture");
  assert.equal(notes[0].image, path.join(folder, "attachments", "shot.png"));
  assert.match(notes[0].excerpt!, /^Body text\./);
  fs.writeFileSync(path.join(folder, "Research", "note-39.md"), text(39).replace("Note 39", "Edited 39"));
  assert.equal((await listNotes(vault))[0].title, "Edited 39 日本語");
  const reads = t.mock.method(fs.promises, "readFile");
  assert.equal((await listNotes(vault)).length, 40);
  assert.equal(reads.mock.callCount(), 0);
  fs.rmSync(folder, { recursive: true });
  assert.deepEqual(await listNotes(vault), []);
  assert.equal(fs.existsSync(folder), true);
  fs.rmSync(root, { recursive: true });
  await assert.rejects(listNotes(vault), /is not at .* any more/);
});
